### ISSUE TITLE
DLCache folders

### ISSUE THREAD

**Issue by Anish-HA** [dataloop-ai/dtlpy#28]
Hey, I have noticed a bug in a previous version of dtlpy where there would be multiple cache directories created on ubuntu due to the "\" symbol in the cache directory name. This was most likely caused by disk_cache ([(https://github.com/dataloop-ai/dtlpy/blame/509fa5f7975b3b7ce6db5d4cdfe06c3af3add758/dtlpy/services/disk_cache.py]) on line 14. I believe this has been fixed in later versions of dtlpy, but I wanted to know if it is safe to delete all previously created directories, i.e. will this affect my upload and download data in the future on dataloop.

 - OS: Ubuntu 20.04
 
 Example image:
![image](https://user-images.githubusercontent.com/63245195/163006655-97da456b-4802-4859-8ab6-4a9664c42ea8.png)
Can I delete these folders without affecting data already on dataloop and locally?

**Comment by orshabtay** [comment]
Hi, thanks for reaching out.
You're right, we had this bug and we fixed it in the next version.
You can safely delete those folders and it won't affect any of your data on the platform.
Let us know if you have any other issues.
