### ISSUE TITLE
Allow user to set the remote file name

### ISSUE THREAD

**Issue by simeoncarstens** [dataloop-ai/dtlpy#3]
When uploading items to a remote data set, the remote file name seems to be fixed to the filename of local file or, when a URL is given, extracted from the URL via a simple `some_url.split('/')[-1]`.
It would be much more user-friendly to allow the user to choose the remote filename themselves. This could be made optional with the default filename set the way it is now.

I ran into this problem when trying to upload an item by passing a Google Cloud Storage signed URL to `Items.upload()`. Related: #4

**Comment by AharonDL** [comment]
Hi @simeoncarstens , I reviewed and approved your PR, good job! 
I will try to add this to next dtlpy release (1.14.4) which should be next week.
Thanks

**Comment by simeoncarstens** [comment]
You're welcome&mdash;glad to hear I could contribute something useful :-)
