### ISSUE TITLE
Not able to download datasets via Python SDK or on the platform

### ISSUE THREAD

**Issue by ankitpt** [dataloop-ai/dtlpy#33]
Receiving following error when trying to download annotated datasets:

`ENOENT: no such file or directory, mkdir '/rubiks-tmp/exports/<DATASET_ID>_<SOME_OTHER_ID>'`

**Comment by IraData11** [comment]
Hi @ankitpt, 
Thank you for reaching out. 
We have checked the download annotation function and didn't find any issues. 

Please make sure that you are following the documentation: 
https://sdk-docs.dataloop.ai/en/latest/entities.html?highlight=download%20dataset#dtlpy.entities.dataset.Dataset.download

https://sdk-docs.dataloop.ai/en/latest/repositories.html?highlight=download%20dataset#dtlpy.repositories.datasets.Datasets.download_annotations

https://github.com/dataloop-ai/dtlpy/blob/21bdce90eb1d37582c16c1c3eebd0717e298911b/dtlpy/entities/dataset.py

If you are still running into the issue, please send us a reproducible version of your script so we can take a look and provide you with guidance.

**Comment by IraData11** [comment]
@ankitpt We wanted to update you that we have found the issue in the backend and already fixed it. Please try again and let us know if you still run into any issues.

**Comment by ankitpt** [comment]
Hi Dataloop team, I am now able to download the datasets. Thank you for the swift action!
