### ISSUE TITLE
Accessing Keyframes

### ISSUE THREAD

**Issue by mattangus** [dataloop-ai/dtlpy#39]
Is there any way to access all the key frames for a video? When I request the annotation json it just has the `snapshots_` field which has every frame labelled with iterpolation. How can I access the non-interpolated data?

**Comment by Gilrl89** [comment]
Hey @mattangus, Thank you for reaching out to us.
Currently, if 'Interpolation' is not used, the "snapshots" will only appear for the annotated frames. To access the information of the "non-interpolated" frames, you will be required to use this script from our SDK for a custom converter : link: https://sdk-docs.dataloop.ai/en/latest/_modules/dtlpy/utilities/converter.html.
If 'Interpolation' is disabled, the position of the annotation/s will remain fixed when moving between frames until an edit is made. In such a scenario, the output for those frames will be the same as that of the last recorded frame (in the output).
Let us know if you have any questions and we would like to guide you through.
