### ISSUE TITLE
Add support for uploading items from cloud platforms

### ISSUE THREAD

**Issue by simeoncarstens** [dataloop-ai/dtlpy#4]
Currently, it looks to me like `dtlpy` does not support adding items from, say, a Google Cloud Storage (GCS) bucket or from S3 AWS storage. This would be very useful to me and most certainly many other users, because the way it is now, one has to, in case of GCS, create a signed URL to a blob and pass that signed URL to `Items.upload()`, which then gets you in trouble because of missing "file names" in signed URLs (related: #3).

**Comment by AharonDL** [comment]
I am closing this issue because it was resolved in #3
