### ISSUE TITLE
Update version of `attrs` dependency?

### ISSUE THREAD

**Issue by tuok** [dataloop-ai/dtlpy#40]
Hello,

I started using `dtlpy` in project of mine and noticed that there's conflict with dependency `attrs`. One specific dependency of my project requires more recent version of `attrs` than currently specified in this repo (`attrs<20.0.0`).

Does `dtlpy` strictly need older version of `attrs`, or would it be possible to update that dependency into a more recent version?

**Comment by Gilrl89** [comment]
Hello,
Thank you for reaching out to us. 
Our team will carefully review your request and work towards finding a solution. If we are able to accommodate your request, it will be included in the upcoming release, scheduled for next week, as long as it does not cause any significant disruptions to our system.
Have a great weekend.

**Comment by tuok** [comment]
Thanks for quick reply, let's hope this change fits in!

Have a good weekend as well!

**Comment by IraData11** [comment]
Hello, 

We have great news! We have updated requirements on our end, so you can use the latest version. 

Let us know if you run into any issues.

**Comment by tuok** [comment]
Thanks a lot! Will be waiting for the official release package. 👍
