### ISSUE TITLE
opencv dependencies on Ubuntu 20.0

### ISSUE THREAD

**Issue by spotiris** [dataloop-ai/dtlpy#6]
The exact opencv_python package required is too specific, and is not available on Ubuntu 20.0.
Suggest changing requirement opencv_python==3.4.2.17 to opencv_python<3.4.9.
I tested this change and it works.

Error message during pip install:
> ERROR: Could not find a version that satisfies the requirement opencv_python==3.4.2.17 (from dtlpy==1.15.11) (from versions: 3.4.8.29, 3.4.9.31, 3.4.9.33, 4.1.2.30, 4.2.0.32, 4.2.0.34)
> ERROR: No matching distribution found for opencv_python==3.4.2.17 (from dtlpy==1.15.11)

**Comment by AharonDL** [comment]
@spotiris 
Done! 
This will be changed in the next dtlpy release.
Thanks for your input
