### ISSUE TITLE
Declared dependency on opencv-python is problematic

### ISSUE THREAD

**Issue by purcell** [dataloop-ai/dtlpy#8]
`opencv-python` is a specific pre-compiled packaging of `cv2`, but other popular packages exist, e.g. `opencv-contrib-python` from the same authors, which contains `cv2` plus extra features.

If a project which is using `opencv-contrib-python` for its extra features tries to also include `dtlpy`, the result will be two incompatible `cv2` modules getting installed, and the project can fail to find the extra contrib features. At my current client, we have encountered this issue, and are unable to use `dtlpy` without maintaining a local fork.

In practice, it it also common for `cv2` to be installed in the Python enviromment using system packaging, in which case pre-compiled python package of opencv from pypi are undesirable.

The suggested resolution would be to remove the explicit dependency on `opencv-python`, and instead note in documentation that `cv2` must be installed by the user, either via system packages or by installing a precompiled version such as `opencv-python` or `opencv-contrib-python`.

Thanks!

**Comment by purcell** [comment]
This appears resolved in 1.16.10 - thanks!

**Comment by AharonDL** [comment]
@purcell we took your advice and removed open-cv requirement. Thank for your feedback!
