### ISSUE TITLE
Can we Auto annotate "Semantic segmentation" model like FCN ,Deeplab

### ISSUE THREAD

**Issue by manish0079** [dataloop-ai/dtlpy#9]
Can we Auto annotate "Semantic segmentation" model ,like u have shown an eg of object detection model Yolo  in documentation is it possible?.
or we simply upload the mask and ten convert it like in the eg : https://docs.dataloop.ai/docs/sdk-convert-types#create-semantic-segmentation-from-image-mask-and-upload

In these Example also i couldn't update the labels properly i am getting an error
like i create a variable and specified the color

labels = [{'label_name': '"car"', 'color': (55,81,246)}, {'label_name': 'traffic sign', 'color': (74,48,136)}]

and uploaded in the recipe as level
and i added in the builder like this

builder.add(annotation_definition=dl.Segmentation(geo=class_mask,
                                                      label=str(labels)))

But i getting an error like whatever recipe is added is not same like 
Can anyone help me in resolving the error 

Thank you

**Comment by dataloop-support** [comment]
<div>Agent Shmulik Eilat linked Freshdesk ticket <a href="https://dataloop.freshdesk.com/a/tickets/740">740</a> for this issue.</div>
